//첫번째 관심목록
//수동적으로 넣어줄거면, id의 범위를 크게 지정해줄것.
const Interest = [
  { _id: 1, name: "연출" },
  { _id: 2, name: "연기" },
  { _id: 3, name: "기획" },
  { _id: 4, name: "제작" },
  { _id: 5, name: "시나리오" },
  { _id: 6, name: "촬영" },
  { _id: 7, name: "조명" },
  { _id: 8, name: "미술" },
  { _id: 9, name: "동시녹음" },
  { _id: 10, name: "편집" },
  { _id: 11, name: "음악" },
  { _id: 12, name: "믹싱" },
  { _id: 13, name: "CG" },
  { _id: 14, name: "자막" },
  { _id: 15, name: "애니메이션" },
  { _id: 16, name: "스토리보드" },
  { _id: 17, name: "그립" },
  { _id: 18, name: "현장편집" },
  { _id: 19, name: "데이터매니저" },
  { _id: 20, name: "홍보&마케팅" },
  { _id: 21, name: "회계" },
  { _id: 22, name: "로케이션" },
  { _id: 23, name: "스테디캠" },
  { _id: 24, name: "DI" },
  { _id: 25, name: "장비대여" },
  { _id: 26, name: "분장" },
  { _id: 27, name: "헤어의상" },
  { _id: 28, name: "소픔" },
  { _id: 29, name: "세트" },
  { _id: 30, name: "스턴트" },
  { _id: 31, name: "스틸" },
  { _id: 32, name: "메이킹" },
  { _id: 33, name: "예고편" },
  { _id: 34, name: "외국어" },
  { _id: 35, name: "특수효과" },
  { _id: 36, name: "특수촬영" },
  { _id: 37, name: "특수분장" },
  { _id: 38, name: "운송" },
  { _id: 39, name: "분장차" },
  { _id: 40, name: "살수차" },
  { _id: 41, name: "발전차" },
  { _id: 42, name: "밥차" },
  { _id: 43, name: "차량대여" },
  { _id: 44, name: "푸드스타일링" },
  { _id: 45, name: "동물조련" },
  { _id: 46, name: "조현물제작" }
];

export { Interest };
